Support order for observer event handlers
wavesurfer-js/wavesurfer.js pull request #2404
Opened 2021-11-13 17:41 UTC by muhammad-sayed-mahdy

### Short description of changes:
- Make `handlers` a sorted set instead of an array.
- Sort the handlers based on their order if exists or the order of insertion.

### Related Issues and other PRs:
[#2390](https://github.com/katspaugh/wavesurfer.js/pull/2390#discussion_r740429675)

2021-11-13 17:48 UTC, muhammad-sayed-mahdy commented
If the used `collections` dependancy is large and you don't want `wavesurfer` to be heavy, and you don't have a suggestion for another package. I have another approach in mind, keep the `handlers` as an array and when firing an event, check if the array is sorted and if it's not, sort it. (most probably it will not be sorted frequently unless someone constantly add handlers or remove them and fire the event)

2021-11-16 22:38 UTC, thijstriemstra commented
> If the used collections dependancy is large and you don't want wavesurfer to be heavy,

How many bytes are we talking about?

2021-11-21 08:37 UTC, muhammad-sayed-mahdy commented
@thijstriemstra it's almost doubled
### Before
wavesurfer.js 215.2 kB
wavesurfer.min.js 72 kB
### After
wavesurfer.js 418.8 kB
wavesurfer.min.js 140.2 kB

2021-11-21 10:59 UTC, thijstriemstra commented
ok yea that is too much for such a small feature

2021-11-21 11:40 UTC, sundayz commented
It's so big because you are using `require` instead of `import` which can do tree shaking (only import the functions that you are using)

2021-11-21 12:25 UTC, muhammad-sayed-mahdy commented
@sundayz I tried it, it's the same

2021-11-21 19:16 UTC, thijstriemstra commented
An es6 `Set` with a sort implementation sounds like most lightweight, e.g. https://stackoverflow.com/a/46267489/11355791 and  https://javascript.plainenglish.io/how-to-sort-a-set-in-javascript-es6-51b53f6ef71a

2021-11-22 11:56 UTC, muhammad-sayed-mahdy commented
@thijstriemstra This will not cause performance issues ? because it will increase the complexity of adding an event handler from O(1) (currently) to O(n log n)
Also I tried to extend the `Set` class and override the `add` method,
```js
export default class SortedSet extends Set {
    constructor(compare) {
        super();
        this.compare = compare;
    }

    add(item) {

        const arr = Array.from( this );
        arr.push( item );
        arr.sort(this.compare);
        this.clear();
        for ( let item of arr ){
            super.add(item);
        }
    }
}
```
 when I tried it, it gave me this error
![image](https://user-images.githubusercontent.com/32793798/142857633-f6f46eac-dea8-41b7-a8bf-51e32ab55c23.png)

I'm not a javascript expert tbh.

2022-01-12 11:48 UTC, thijstriemstra commented
what's the plan for this PR @muhammad-sayed-mahdy?

2022-01-12 18:35 UTC, muhammad-sayed-mahdy commented
I don't know, I just need some help, anyway the issue is in the implementation, but the idea is valid and based on it, #2307 will be solved

2022-02-26 15:48 UTC, muhammad-sayed-mahdy commented
@thijstriemstra turns out that this error was because I just forgot to run `npm install` :sweat_smile: sorry for that.
However I think this implementation will increase the complexity of adding a handler from `O(1)` (in the case of the array), to `O(n log n)` in case of sorting every time when inserting a handler.

2022-03-07 18:21 UTC, thijstriemstra commented
> However I think this implementation will increase the complexity of adding a handler from O(1) (in the case of the array), to O(n log n) in case of sorting every time when inserting a handler.

I guess we need to keep searching for a better, small size library..

2023-03-07 15:47 UTC, entonbiba requested changes
I don't think we need this library to simply do the sorted set. We can rewrite it in js directly which will be very small.

2023-03-07 15:56 UTC, entonbiba commented on src/util/observer.js
>                  if (a.order && b.order && a.order != b.order) {
would it be better to do `if (a.order && b.order && a.order !== b.order)` ?

2023-03-08 07:52 UTC, katspaugh commented
I don’t think this is a good solution to the linked issue. If certain events need to be fired in a certain order, the code that triggers them should call the fire method in that order, topologically speaking.

2023-03-08 09:28 UTC, closed without merging