Release 6.6.0
wavesurfer-js/wavesurfer.js pull request #2715
Opened 2023-03-12 09:27 UTC by katspaugh

6.6.0 (12.03.2023)
------------------
- [Regions] Fix undefined content element on remove (#2713)
- Zoom optimisation for Waves and matching implementation for Spectrograms (#2646)
- Fix: release workflow permissions (#2709)

2023-03-12 16:14 UTC, katspaugh commented
I had to publish 6.5.2 in the meanwhile because I had accidentally published an alpha version w/o the corresponding npm tag. Now it's back to normal.

2023-03-13 02:38 UTC, thijstriemstra commented
> I had to publish 6.5.2 in the meanwhile because I had accidentally published an alpha version w/o the corresponding npm tag. Now it's back to normal.

I have the feeling you're rushing a lot of things (merges, reviews, releases); why? These things would've been caught with simple reviews, right?

2023-03-13 05:46 UTC, katspaugh commented
Yes, I definitely rushed things. Partly because I only have limited time on the weekend, and want to get as much things done as possible.
I mistakenly ran `npm publish` instead of `npm publish --tag alpha`.
Anyway, not an excuse to bypass reviews.

2023-03-13 22:22 UTC, thijstriemstra approved these changes

2023-03-13 22:24 UTC, thijstriemstra requested changes

2023-03-13 22:24 UTC, thijstriemstra commented on CHANGES.md
> +- [Regions] Fix undefined content element on remove (#2713)
[Regions] should be  in a separate list (see other changelogs below for example)

2023-03-14 17:47 UTC, thijstriemstra approved these changes

2023-03-14 19:56 UTC, merged

2023-03-14 20:00 UTC, katspaugh commented
Looks like I broke the npm publish part of the deployment action.
https://github.com/wavesurfer-js/wavesurfer.js/actions/runs/4419688300/jobs/7748430370
Will publish manually at this time, and fix the action later.

2023-03-14 20:03 UTC, katspaugh commented
Created an issue: #2723.